/**
 * Conformance tests for pdftotext — PDF text extraction WASM binary.
 *
 * Tests cover: basic extraction, multi-page with form-feeds, -nopgbrk,
 * page range (-f/-l), output-to-file, stdout (-), and the real-world
 * "Attention Is All You Need" arxiv paper (1706.03762).
 */
import { describe, it, beforeEach } from '@std/testing/bdd';
import { expect } from '@std/expect';
import { resolve } from 'node:path';
import { readFileSync, existsSync } from 'node:fs';

import { ShellInstance } from '../../shell-instance.js';
import { ProcessManager } from '../../../process/manager.js';
import { VFS } from '../../../vfs/vfs.js';
import { NodeAdapter } from '../../../platform/node-adapter.js';

const FIXTURES = resolve(import.meta.dirname!, '../../../platform/__tests__/fixtures');
const SHELL_FIXTURES = resolve(import.meta.dirname!, '../fixtures');
const SHELL_EXEC_WASM = resolve(SHELL_FIXTURES, 'codepod-shell-exec.wasm');

const TOOLS = ['cat', 'echo', 'ls', 'pdftotext'];

// ---------------------------------------------------------------------------
// Minimal synthetic PDFs (generated by packages/pdf-tools/src/bin/gen-test-pdf.rs)
// ---------------------------------------------------------------------------

/** Single page with "Hello World" */
const ONE_PAGE_PDF =
  'JVBERi0xLjQKMSAwIG9iago8PCAvVHlwZSAvQ2F0YWxvZyAvUGFnZXMgMiAwIFIgPj4KZW5kb2JqCjIgMCBvYmoKPDwgL1R5cGUgL1BhZ2VzIC9LaWRzIFszIDAgUl0gL0NvdW50IDEgPj4KZW5kb2JqCjMgMCBvYmoKPDwgL1R5cGUgL1BhZ2UgL1BhcmVudCAyIDAgUiAvTWVkaWFCb3ggWzAgMCA2MTIgNzkyXSAvQ29udGVudHMgNCAwIFIgL1Jlc291cmNlcyA8PCAvRm9udCA8PCAvRjEgNSAwIFIgPj4gPj4gPj4KZW5kb2JqCjQgMCBvYmoKPDwgL0xlbmd0aCA0NCA+PgpzdHJlYW0KQlQKL0YxIDEyIFRmCjEwMCA3MDAgVGQgKEhlbGxvIFdvcmxkKSBUagpFVAoKZW5kc3RyZWFtCmVuZG9iago1IDAgb2JqCjw8IC9UeXBlIC9Gb250IC9TdWJ0eXBlIC9UeXBlMSAvQmFzZUZvbnQgL0NvdXJpZXIgPj4KZW5kb2JqCnhyZWYKMCA2CjAwMDAwMDAwMDAgNjU1MzUgZiAKMDAwMDAwMDAwOSAwMDAwMCBuIAowMDAwMDAwMDU4IDAwMDAwIG4gCjAwMDAwMDAxMTUgMDAwMDAgbiAKMDAwMDAwMDI0MSAwMDAwMCBuIAowMDAwMDAwMzM1IDAwMDAwIG4gCnRyYWlsZXIKPDwgL1NpemUgNiAvUm9vdCAxIDAgUiA+PgpzdGFydHhyZWYKNDAzCiUlRU9GCg==';

/** Two pages: "Page one text" and "Page two text" */
const TWO_PAGE_PDF =
  'JVBERi0xLjQKMSAwIG9iago8PCAvVHlwZSAvQ2F0YWxvZyAvUGFnZXMgMiAwIFIgPj4KZW5kb2JqCjIgMCBvYmoKPDwgL1R5cGUgL1BhZ2VzIC9LaWRzIFszIDAgUiA0IDAgUl0gL0NvdW50IDIgPj4KZW5kb2JqCjMgMCBvYmoKPDwgL1R5cGUgL1BhZ2UgL1BhcmVudCAyIDAgUiAvTWVkaWFCb3ggWzAgMCA2MTIgNzkyXSAvQ29udGVudHMgNSAwIFIgL1Jlc291cmNlcyA8PCAvRm9udCA8PCAvRjEgNyAwIFIgPj4gPj4gPj4KZW5kb2JqCjQgMCBvYmoKPDwgL1R5cGUgL1BhZ2UgL1BhcmVudCAyIDAgUiAvTWVkaWFCb3ggWzAgMCA2MTIgNzkyXSAvQ29udGVudHMgNiAwIFIgL1Jlc291cmNlcyA8PCAvRm9udCA8PCAvRjEgNyAwIFIgPj4gPj4gPj4KZW5kb2JqCjUgMCBvYmoKPDwgL0xlbmd0aCA0NiA+PgpzdHJlYW0KQlQKL0YxIDEyIFRmCjEwMCA3MDAgVGQgKFBhZ2Ugb25lIHRleHQpIFRqCkVUCgplbmRzdHJlYW0KZW5kb2JqCjYgMCBvYmoKPDwgL0xlbmd0aCA0NiA+PgpzdHJlYW0KQlQKL0YxIDEyIFRmCjEwMCA3MDAgVGQgKFBhZ2UgdHdvIHRleHQpIFRqCkVUCgplbmRzdHJlYW0KZW5kb2JqCjcgMCBvYmoKPDwgL1R5cGUgL0ZvbnQgL1N1YnR5cGUgL1R5cGUxIC9CYXNlRm9udCAvQ291cmllciA+PgplbmRvYmoKeHJlZgowIDgKMDAwMDAwMDAwMCA2NTUzNSBmIAowMDAwMDAwMDA5IDAwMDAwIG4gCjAwMDAwMDAwNTggMDAwMDAgbiAKMDAwMDAwMDEyMSAwMDAwMCBuIAowMDAwMDAwMjQ3IDAwMDAwIG4gCjAwMDAwMDAzNzMgMDAwMDAgbiAKMDAwMDAwMDQ2OSAwMDAwMCBuIAowMDAwMDAwNTY1IDAwMDAwIG4gCnRyYWlsZXIKPDwgL1NpemUgOCAvUm9vdCAxIDAgUiA+PgpzdGFydHhyZWYKNjMzCiUlRU9GCg==';

/** Three pages: "First page", "Second page", "Third page" */
const THREE_PAGE_PDF =
  'JVBERi0xLjQKMSAwIG9iago8PCAvVHlwZSAvQ2F0YWxvZyAvUGFnZXMgMiAwIFIgPj4KZW5kb2JqCjIgMCBvYmoKPDwgL1R5cGUgL1BhZ2VzIC9LaWRzIFszIDAgUiA0IDAgUiA1IDAgUl0gL0NvdW50IDMgPj4KZW5kb2JqCjMgMCBvYmoKPDwgL1R5cGUgL1BhZ2UgL1BhcmVudCAyIDAgUiAvTWVkaWFCb3ggWzAgMCA2MTIgNzkyXSAvQ29udGVudHMgNiAwIFIgL1Jlc291cmNlcyA8PCAvRm9udCA8PCAvRjEgOSAwIFIgPj4gPj4gPj4KZW5kb2JqCjQgMCBvYmoKPDwgL1R5cGUgL1BhZ2UgL1BhcmVudCAyIDAgUiAvTWVkaWFCb3ggWzAgMCA2MTIgNzkyXSAvQ29udGVudHMgNyAwIFIgL1Jlc291cmNlcyA8PCAvRm9udCA8PCAvRjEgOSAwIFIgPj4gPj4gPj4KZW5kb2JqCjUgMCBvYmoKPDwgL1R5cGUgL1BhZ2UgL1BhcmVudCAyIDAgUiAvTWVkaWFCb3ggWzAgMCA2MTIgNzkyXSAvQ29udGVudHMgOCAwIFIgL1Jlc291cmNlcyA8PCAvRm9udCA8PCAvRjEgOSAwIFIgPj4gPj4gPj4KZW5kb2JqCjYgMCBvYmoKPDwgL0xlbmd0aCA0MyA+PgpzdHJlYW0KQlQKL0YxIDEyIFRmCjEwMCA3MDAgVGQgKEZpcnN0IHBhZ2UpIFRqCkVUCgplbmRzdHJlYW0KZW5kb2JqCjcgMCBvYmoKPDwgL0xlbmd0aCA0NCA+PgpzdHJlYW0KQlQKL0YxIDEyIFRmCjEwMCA3MDAgVGQgKFNlY29uZCBwYWdlKSBUagpFVAoKZW5kc3RyZWFtCmVuZG9iago4IDAgb2JqCjw8IC9MZW5ndGggNDMgPj4Kc3RyZWFtCkJUCi9GMSAxMiBUZgoxMDAgNzAwIFRkIChUaGlyZCBwYWdlKSBUagpFVAoKZW5kc3RyZWFtCmVuZG9iago5IDAgb2JqCjw8IC9UeXBlIC9Gb250IC9TdWJ0eXBlIC9UeXBlMSAvQmFzZUZvbnQgL0NvdXJpZXIgPj4KZW5kb2JqCnhyZWYKMCAxMAowMDAwMDAwMDAwIDY1NTM1IGYgCjAwMDAwMDAwMDkgMDAwMDAgbiAKMDAwMDAwMDA1OCAwMDAwMCBuIAowMDAwMDAwMTI3IDAwMDAwIG4gCjAwMDAwMDAyNTMgMDAwMDAgbiAKMDAwMDAwMDM3OSAwMDAwMCBuIAowMDAwMDAwNTA1IDAwMDAwIG4gCjAwMDAwMDA1OTggMDAwMDAgbiAKMDAwMDAwMDY5MiAwMDAwMCBuIAowMDAwMDAwNzg1IDAwMDAwIG4gCnRyYWlsZXIKPDwgL1NpemUgMTAgL1Jvb3QgMSAwIFIgPj4Kc3RhcnR4cmVmCjg1MwolJUVPRgo=';

// Real-world arxiv fixture (arxiv 1706.03762 — "Attention Is All You Need")
// Stored at: packages/orchestrator/src/shell/__tests__/fixtures/attention.pdf
const ATTENTION_PDF_PATH = resolve(SHELL_FIXTURES, 'attention.pdf');
const ATTENTION_PDF_BYTES: Uint8Array | null = existsSync(ATTENTION_PDF_PATH)
  ? new Uint8Array(readFileSync(ATTENTION_PDF_PATH))
  : null;

function b64decode(b64: string): Uint8Array {
  const bin = atob(b64);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return bytes;
}

// ---------------------------------------------------------------------------
// Test setup
// ---------------------------------------------------------------------------

describe('pdftotext conformance', () => {
  let vfs: VFS;
  let runner: ShellInstance;

  beforeEach(async () => {
    vfs = new VFS();
    const adapter = new NodeAdapter();
    const mgr = new ProcessManager(vfs, adapter);

    for (const tool of TOOLS) {
      mgr.registerTool(tool, resolve(FIXTURES, `${tool}.wasm`));
    }

    await mgr.preloadModules();
    runner = await ShellInstance.create(vfs, mgr, adapter, SHELL_EXEC_WASM, {
      syncSpawn: (cmd, args, env, stdin, cwd) =>
        mgr.spawnSync(cmd, args, env, stdin, cwd),
    });

    vfs.writeFile('/tmp/one.pdf', b64decode(ONE_PAGE_PDF));
    vfs.writeFile('/tmp/two.pdf', b64decode(TWO_PAGE_PDF));
    vfs.writeFile('/tmp/three.pdf', b64decode(THREE_PAGE_PDF));
    if (ATTENTION_PDF_BYTES) {
      vfs.writeFile('/tmp/attention.pdf', ATTENTION_PDF_BYTES);
    }
  });

  // -------------------------------------------------------------------------
  // Basic extraction
  // -------------------------------------------------------------------------

  describe('basic text extraction', () => {
    it('extracts text from a single-page PDF to stdout', async () => {
      const r = await runner.run('pdftotext /tmp/one.pdf -');
      expect(r.exitCode).toBe(0);
      expect(r.stdout).toContain('Hello World');
    });

    it('exit 0 on success', async () => {
      const r = await runner.run('pdftotext /tmp/one.pdf -');
      expect(r.exitCode).toBe(0);
    });

    it('prints nothing to stderr on success', async () => {
      const r = await runner.run('pdftotext /tmp/one.pdf -');
      expect(r.stderr).toBe('');
    });
  });

  // -------------------------------------------------------------------------
  // Multi-page and page breaks
  // -------------------------------------------------------------------------

  describe('multi-page PDFs', () => {
    it('extracts text from both pages', async () => {
      const r = await runner.run('pdftotext /tmp/two.pdf -');
      expect(r.exitCode).toBe(0);
      expect(r.stdout).toContain('Page one text');
      expect(r.stdout).toContain('Page two text');
    });

    it('inserts form-feed (\\f) between pages by default', async () => {
      const r = await runner.run('pdftotext /tmp/two.pdf -');
      expect(r.exitCode).toBe(0);
      expect(r.stdout).toContain('\f');
    });

    it('-nopgbrk suppresses form-feed separators', async () => {
      const r = await runner.run('pdftotext -nopgbrk /tmp/two.pdf -');
      expect(r.exitCode).toBe(0);
      expect(r.stdout).not.toContain('\f');
      expect(r.stdout).toContain('Page one text');
      expect(r.stdout).toContain('Page two text');
    });

    it('page 1 appears before page 2 in output', async () => {
      const r = await runner.run('pdftotext /tmp/two.pdf -');
      expect(r.exitCode).toBe(0);
      const pos1 = r.stdout.indexOf('Page one text');
      const pos2 = r.stdout.indexOf('Page two text');
      expect(pos1).toBeGreaterThanOrEqual(0);
      expect(pos2).toBeGreaterThanOrEqual(0);
      expect(pos1).toBeLessThan(pos2);
    });
  });

  // -------------------------------------------------------------------------
  // Page range selection
  // -------------------------------------------------------------------------

  describe('page range (-f and -l)', () => {
    it('-f 2 skips the first page', async () => {
      const r = await runner.run('pdftotext -f 2 /tmp/two.pdf -');
      expect(r.exitCode).toBe(0);
      expect(r.stdout).not.toContain('Page one text');
      expect(r.stdout).toContain('Page two text');
    });

    it('-l 1 extracts only the first page', async () => {
      const r = await runner.run('pdftotext -l 1 /tmp/two.pdf -');
      expect(r.exitCode).toBe(0);
      expect(r.stdout).toContain('Page one text');
      expect(r.stdout).not.toContain('Page two text');
    });

    it('-f 2 -l 2 extracts only the middle page from a 3-page PDF', async () => {
      const r = await runner.run('pdftotext -f 2 -l 2 /tmp/three.pdf -');
      expect(r.exitCode).toBe(0);
      expect(r.stdout).not.toContain('First page');
      expect(r.stdout).toContain('Second page');
      expect(r.stdout).not.toContain('Third page');
    });

    it('-f 1 -l 3 extracts all three pages', async () => {
      const r = await runner.run('pdftotext -f 1 -l 3 /tmp/three.pdf -');
      expect(r.exitCode).toBe(0);
      expect(r.stdout).toContain('First page');
      expect(r.stdout).toContain('Second page');
      expect(r.stdout).toContain('Third page');
    });
  });

  // -------------------------------------------------------------------------
  // Output file handling
  // -------------------------------------------------------------------------

  describe('output file handling', () => {
    it('writes to <stem>.txt by default when no output file specified', async () => {
      const r = await runner.run('pdftotext /tmp/one.pdf');
      expect(r.exitCode).toBe(0);
      const out = new TextDecoder().decode(vfs.readFile('/tmp/one.txt'));
      expect(out).toContain('Hello World');
    });

    it('writes to an explicit output file path', async () => {
      const r = await runner.run('pdftotext /tmp/one.pdf /tmp/myout.txt');
      expect(r.exitCode).toBe(0);
      const out = new TextDecoder().decode(vfs.readFile('/tmp/myout.txt'));
      expect(out).toContain('Hello World');
    });

    it('- as output file sends text to stdout', async () => {
      const r = await runner.run('pdftotext /tmp/one.pdf -');
      expect(r.exitCode).toBe(0);
      expect(r.stdout).toContain('Hello World');
    });
  });

  // -------------------------------------------------------------------------
  // Error handling
  // -------------------------------------------------------------------------

  describe('error handling', () => {
    it('exits non-zero for a missing file', async () => {
      const r = await runner.run('pdftotext /tmp/no-such-file.pdf -');
      expect(r.exitCode).not.toBe(0);
    });

    it('prints the filename in stderr for a missing file', async () => {
      const r = await runner.run('pdftotext /tmp/no-such-file.pdf -');
      expect(r.stderr).toContain('no-such-file.pdf');
    });

    it('-h prints usage and exits 0', async () => {
      const r = await runner.run('pdftotext -h');
      expect(r.exitCode).toBe(0);
      expect(r.stdout).toContain('pdftotext');
    });
  });

  // -------------------------------------------------------------------------
  // Real-world: "Attention Is All You Need" (arxiv 1706.03762)
  // 15-page transformer paper stored as:
  //   packages/orchestrator/src/shell/__tests__/fixtures/attention.pdf
  // -------------------------------------------------------------------------

  describe('real-world: Attention Is All You Need (arxiv 1706.03762)', () => {
    it('extracts the paper title from page 1', async () => {
      if (!ATTENTION_PDF_BYTES) return; // skip if fixture not available
      const r = await runner.run('pdftotext -f 1 -l 1 /tmp/attention.pdf -');
      expect(r.exitCode).toBe(0);
      expect(r.stdout).toContain('Attention Is All You Need');
    });

    it('extracts author names from page 1', async () => {
      if (!ATTENTION_PDF_BYTES) return;
      const r = await runner.run('pdftotext -f 1 -l 1 /tmp/attention.pdf -');
      expect(r.exitCode).toBe(0);
      // Known authors of the paper
      expect(r.stdout).toContain('Vaswani');
    });

    it('produces form-feeds for a 3-page range', async () => {
      if (!ATTENTION_PDF_BYTES) return;
      const r = await runner.run('pdftotext -f 1 -l 3 /tmp/attention.pdf -');
      expect(r.exitCode).toBe(0);
      const formFeeds = (r.stdout.match(/\f/g) ?? []).length;
      expect(formFeeds).toBe(3);
    });

    it('-nopgbrk removes all form-feeds', async () => {
      if (!ATTENTION_PDF_BYTES) return;
      const r = await runner.run('pdftotext -nopgbrk -f 1 -l 3 /tmp/attention.pdf -');
      expect(r.exitCode).toBe(0);
      expect(r.stdout).not.toContain('\f');
    });

    it('outputs substantially more text than a single page when extracting all 15 pages', async () => {
      if (!ATTENTION_PDF_BYTES) return;
      const r = await runner.run('pdftotext /tmp/attention.pdf -');
      expect(r.exitCode).toBe(0);
      // 15 pages of a research paper should produce thousands of characters
      expect(r.stdout.length).toBeGreaterThan(10000);
    });
  });
});
