/**
 * Conformance tests for pdftotext — PDF text extraction WASM binary.
 *
 * Spec reference: Poppler pdftotext (https://poppler.freedesktop.org)
 * Tested against: pdftotext version 26.03.0
 *
 * Known deviations from Poppler that are intentional:
 *   - Text extraction quality differs (lopdf vs Poppler's layout engine)
 *   - Layout flags (-layout, -raw, -tsv, etc.) are accepted but ignored
 *
 * Spec behaviors verified here:
 *   - -h/-help/--help print to stderr and exit 0
 *   - -v prints to stderr and exits 0
 *   - No args prints help to stderr and exits 99
 *   - -f/-l page range selection
 *   - -nopgbrk suppresses form-feeds
 *   - Form-feed (\f) after every page including the last
 *   - Default output to <stem>.txt next to the input file
 *   - '-' as output sends to stdout
 *   - Missing file exits 1
 */
import { describe, it, beforeEach } from '@std/testing/bdd';
import { expect } from '@std/expect';
import { resolve } from 'node:path';
import { readFileSync, existsSync } from 'node:fs';

import { ShellInstance } from '../../shell-instance.js';
import { ProcessManager } from '../../../process/manager.js';
import { VFS } from '../../../vfs/vfs.js';
import { NodeAdapter } from '../../../platform/node-adapter.js';

const FIXTURES = resolve(import.meta.dirname!, '../../../platform/__tests__/fixtures');
const SHELL_FIXTURES = resolve(import.meta.dirname!, '../fixtures');
const SHELL_EXEC_WASM = resolve(SHELL_FIXTURES, 'codepod-shell-exec.wasm');

const TOOLS = ['cat', 'echo', 'ls', 'pdftotext'];

// ---------------------------------------------------------------------------
// Minimal synthetic PDFs (generated by packages/pdf-tools/src/bin/gen-test-pdf.rs)
// ---------------------------------------------------------------------------

/** Single page with "Hello World" */
const ONE_PAGE_PDF =
  'JVBERi0xLjQKMSAwIG9iago8PCAvVHlwZSAvQ2F0YWxvZyAvUGFnZXMgMiAwIFIgPj4KZW5kb2JqCjIgMCBvYmoKPDwgL1R5cGUgL1BhZ2VzIC9LaWRzIFszIDAgUl0gL0NvdW50IDEgPj4KZW5kb2JqCjMgMCBvYmoKPDwgL1R5cGUgL1BhZ2UgL1BhcmVudCAyIDAgUiAvTWVkaWFCb3ggWzAgMCA2MTIgNzkyXSAvQ29udGVudHMgNCAwIFIgL1Jlc291cmNlcyA8PCAvRm9udCA8PCAvRjEgNSAwIFIgPj4gPj4gPj4KZW5kb2JqCjQgMCBvYmoKPDwgL0xlbmd0aCA0NCA+PgpzdHJlYW0KQlQKL0YxIDEyIFRmCjEwMCA3MDAgVGQgKEhlbGxvIFdvcmxkKSBUagpFVAoKZW5kc3RyZWFtCmVuZG9iago1IDAgb2JqCjw8IC9UeXBlIC9Gb250IC9TdWJ0eXBlIC9UeXBlMSAvQmFzZUZvbnQgL0NvdXJpZXIgPj4KZW5kb2JqCnhyZWYKMCA2CjAwMDAwMDAwMDAgNjU1MzUgZiAKMDAwMDAwMDAwOSAwMDAwMCBuIAowMDAwMDAwMDU4IDAwMDAwIG4gCjAwMDAwMDAxMTUgMDAwMDAgbiAKMDAwMDAwMDI0MSAwMDAwMCBuIAowMDAwMDAwMzM1IDAwMDAwIG4gCnRyYWlsZXIKPDwgL1NpemUgNiAvUm9vdCAxIDAgUiA+PgpzdGFydHhyZWYKNDAzCiUlRU9GCg==';

/** Two pages: "Page one text" and "Page two text" */
const TWO_PAGE_PDF =
  'JVBERi0xLjQKMSAwIG9iago8PCAvVHlwZSAvQ2F0YWxvZyAvUGFnZXMgMiAwIFIgPj4KZW5kb2JqCjIgMCBvYmoKPDwgL1R5cGUgL1BhZ2VzIC9LaWRzIFszIDAgUiA0IDAgUl0gL0NvdW50IDIgPj4KZW5kb2JqCjMgMCBvYmoKPDwgL1R5cGUgL1BhZ2UgL1BhcmVudCAyIDAgUiAvTWVkaWFCb3ggWzAgMCA2MTIgNzkyXSAvQ29udGVudHMgNSAwIFIgL1Jlc291cmNlcyA8PCAvRm9udCA8PCAvRjEgNyAwIFIgPj4gPj4gPj4KZW5kb2JqCjQgMCBvYmoKPDwgL1R5cGUgL1BhZ2UgL1BhcmVudCAyIDAgUiAvTWVkaWFCb3ggWzAgMCA2MTIgNzkyXSAvQ29udGVudHMgNiAwIFIgL1Jlc291cmNlcyA8PCAvRm9udCA8PCAvRjEgNyAwIFIgPj4gPj4gPj4KZW5kb2JqCjUgMCBvYmoKPDwgL0xlbmd0aCA0NiA+PgpzdHJlYW0KQlQKL0YxIDEyIFRmCjEwMCA3MDAgVGQgKFBhZ2Ugb25lIHRleHQpIFRqCkVUCgplbmRzdHJlYW0KZW5kb2JqCjYgMCBvYmoKPDwgL0xlbmd0aCA0NiA+PgpzdHJlYW0KQlQKL0YxIDEyIFRmCjEwMCA3MDAgVGQgKFBhZ2UgdHdvIHRleHQpIFRqCkVUCgplbmRzdHJlYW0KZW5kb2JqCjcgMCBvYmoKPDwgL1R5cGUgL0ZvbnQgL1N1YnR5cGUgL1R5cGUxIC9CYXNlRm9udCAvQ291cmllciA+PgplbmRvYmoKeHJlZgowIDgKMDAwMDAwMDAwMCA2NTUzNSBmIAowMDAwMDAwMDA5IDAwMDAwIG4gCjAwMDAwMDAwNTggMDAwMDAgbiAKMDAwMDAwMDEyMSAwMDAwMCBuIAowMDAwMDAwMjQ3IDAwMDAwIG4gCjAwMDAwMDAzNzMgMDAwMDAgbiAKMDAwMDAwMDQ2OSAwMDAwMCBuIAowMDAwMDAwNTY1IDAwMDAwIG4gCnRyYWlsZXIKPDwgL1NpemUgOCAvUm9vdCAxIDAgUiA+PgpzdGFydHhyZWYKNjMzCiUlRU9GCg==';

/** Three pages: "First page", "Second page", "Third page" */
const THREE_PAGE_PDF =
  'JVBERi0xLjQKMSAwIG9iago8PCAvVHlwZSAvQ2F0YWxvZyAvUGFnZXMgMiAwIFIgPj4KZW5kb2JqCjIgMCBvYmoKPDwgL1R5cGUgL1BhZ2VzIC9LaWRzIFszIDAgUiA0IDAgUiA1IDAgUl0gL0NvdW50IDMgPj4KZW5kb2JqCjMgMCBvYmoKPDwgL1R5cGUgL1BhZ2UgL1BhcmVudCAyIDAgUiAvTWVkaWFCb3ggWzAgMCA2MTIgNzkyXSAvQ29udGVudHMgNiAwIFIgL1Jlc291cmNlcyA8PCAvRm9udCA8PCAvRjEgOSAwIFIgPj4gPj4gPj4KZW5kb2JqCjQgMCBvYmoKPDwgL1R5cGUgL1BhZ2UgL1BhcmVudCAyIDAgUiAvTWVkaWFCb3ggWzAgMCA2MTIgNzkyXSAvQ29udGVudHMgNyAwIFIgL1Jlc291cmNlcyA8PCAvRm9udCA8PCAvRjEgOSAwIFIgPj4gPj4gPj4KZW5kb2JqCjUgMCBvYmoKPDwgL1R5cGUgL1BhZ2UgL1BhcmVudCAyIDAgUiAvTWVkaWFCb3ggWzAgMCA2MTIgNzkyXSAvQ29udGVudHMgOCAwIFIgL1Jlc291cmNlcyA8PCAvRm9udCA8PCAvRjEgOSAwIFIgPj4gPj4gPj4KZW5kb2JqCjYgMCBvYmoKPDwgL0xlbmd0aCA0MyA+PgpzdHJlYW0KQlQKL0YxIDEyIFRmCjEwMCA3MDAgVGQgKEZpcnN0IHBhZ2UpIFRqCkVUCgplbmRzdHJlYW0KZW5kb2JqCjcgMCBvYmoKPDwgL0xlbmd0aCA0NCA+PgpzdHJlYW0KQlQKL0YxIDEyIFRmCjEwMCA3MDAgVGQgKFNlY29uZCBwYWdlKSBUagpFVAoKZW5kc3RyZWFtCmVuZG9iago4IDAgb2JqCjw8IC9MZW5ndGggNDMgPj4Kc3RyZWFtCkJUCi9GMSAxMiBUZgoxMDAgNzAwIFRkIChUaGlyZCBwYWdlKSBUagpFVAoKZW5kc3RyZWFtCmVuZG9iago5IDAgb2JqCjw8IC9UeXBlIC9Gb250IC9TdWJ0eXBlIC9UeXBlMSAvQmFzZUZvbnQgL0NvdXJpZXIgPj4KZW5kb2JqCnhyZWYKMCAxMAowMDAwMDAwMDAwIDY1NTM1IGYgCjAwMDAwMDAwMDkgMDAwMDAgbiAKMDAwMDAwMDA1OCAwMDAwMCBuIAowMDAwMDAwMTI3IDAwMDAwIG4gCjAwMDAwMDAyNTMgMDAwMDAgbiAKMDAwMDAwMDM3OSAwMDAwMCBuIAowMDAwMDAwNTA1IDAwMDAwIG4gCjAwMDAwMDA1OTggMDAwMDAgbiAKMDAwMDAwMDY5MiAwMDAwMCBuIAowMDAwMDAwNzg1IDAwMDAwIG4gCnRyYWlsZXIKPDwgL1NpemUgMTAgL1Jvb3QgMSAwIFIgPj4Kc3RhcnR4cmVmCjg1MwolJUVPRgo=';

// Real-world arxiv fixture (arxiv 1706.03762 — "Attention Is All You Need")
// Stored at: packages/orchestrator/src/shell/__tests__/fixtures/attention.pdf
const ATTENTION_PDF_PATH = resolve(SHELL_FIXTURES, 'attention.pdf');
const ATTENTION_PDF_BYTES: Uint8Array | null = existsSync(ATTENTION_PDF_PATH)
  ? new Uint8Array(readFileSync(ATTENTION_PDF_PATH))
  : null;

function b64decode(b64: string): Uint8Array {
  const bin = atob(b64);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return bytes;
}

// ---------------------------------------------------------------------------
// Test setup
// ---------------------------------------------------------------------------

describe('pdftotext conformance', () => {
  let vfs: VFS;
  let runner: ShellInstance;

  beforeEach(async () => {
    vfs = new VFS();
    const adapter = new NodeAdapter();
    const mgr = new ProcessManager(vfs, adapter);

    for (const tool of TOOLS) {
      mgr.registerTool(tool, resolve(FIXTURES, `${tool}.wasm`));
    }

    await mgr.preloadModules();
    runner = await ShellInstance.create(vfs, mgr, adapter, SHELL_EXEC_WASM, {
      syncSpawn: (cmd, args, env, stdin, cwd) =>
        mgr.spawnSync(cmd, args, env, stdin, cwd),
    });

    vfs.writeFile('/tmp/one.pdf', b64decode(ONE_PAGE_PDF));
    vfs.writeFile('/tmp/two.pdf', b64decode(TWO_PAGE_PDF));
    vfs.writeFile('/tmp/three.pdf', b64decode(THREE_PAGE_PDF));
    if (ATTENTION_PDF_BYTES) {
      vfs.writeFile('/tmp/attention.pdf', ATTENTION_PDF_BYTES);
    }
  });

  // -------------------------------------------------------------------------
  // Spec: help and version output
  // Poppler: -h/-help/--help → stderr, exit 0
  //          -v             → stderr, exit 0
  //          no args        → stderr, exit 99
  // -------------------------------------------------------------------------

  describe('spec: help and version output', () => {
    it('-h prints usage to stderr and exits 0', async () => {
      const r = await runner.run('pdftotext -h');
      expect(r.exitCode).toBe(0);
      expect(r.stderr).toContain('pdftotext');
      expect(r.stdout).toBe('');
    });

    it('-help prints usage to stderr and exits 0', async () => {
      const r = await runner.run('pdftotext -help');
      expect(r.exitCode).toBe(0);
      expect(r.stderr).toContain('pdftotext');
      expect(r.stdout).toBe('');
    });

    it('--help prints usage to stderr and exits 0', async () => {
      const r = await runner.run('pdftotext --help');
      expect(r.exitCode).toBe(0);
      expect(r.stderr).toContain('pdftotext');
      expect(r.stdout).toBe('');
    });

    it('-v prints version to stderr and exits 0', async () => {
      const r = await runner.run('pdftotext -v');
      expect(r.exitCode).toBe(0);
      expect(r.stderr).toContain('pdftotext');
      expect(r.stdout).toBe('');
    });

    it('no args prints help to stderr and exits 99', async () => {
      const r = await runner.run('pdftotext');
      expect(r.exitCode).toBe(99);
      expect(r.stderr).toContain('pdftotext');
      expect(r.stdout).toBe('');
    });
  });

  // -------------------------------------------------------------------------
  // Spec: core extraction flags
  // -------------------------------------------------------------------------

  describe('spec: core flags (-f, -l, -nopgbrk, stdout)', () => {
    it('extracts text and sends to stdout with -', async () => {
      const r = await runner.run('pdftotext /tmp/one.pdf -');
      expect(r.exitCode).toBe(0);
      expect(r.stdout).toContain('Hello World');
      expect(r.stderr).toBe('');
    });

    it('-f first page to convert', async () => {
      const r = await runner.run('pdftotext -f 2 /tmp/two.pdf -');
      expect(r.exitCode).toBe(0);
      expect(r.stdout).not.toContain('Page one text');
      expect(r.stdout).toContain('Page two text');
    });

    it('-l last page to convert', async () => {
      const r = await runner.run('pdftotext -l 1 /tmp/two.pdf -');
      expect(r.exitCode).toBe(0);
      expect(r.stdout).toContain('Page one text');
      expect(r.stdout).not.toContain('Page two text');
    });

    it('-f and -l together select a range', async () => {
      const r = await runner.run('pdftotext -f 2 -l 2 /tmp/three.pdf -');
      expect(r.exitCode).toBe(0);
      expect(r.stdout).not.toContain('First page');
      expect(r.stdout).toContain('Second page');
      expect(r.stdout).not.toContain('Third page');
    });

    it('-nopgbrk suppresses form-feed characters', async () => {
      const r = await runner.run('pdftotext -nopgbrk /tmp/two.pdf -');
      expect(r.exitCode).toBe(0);
      expect(r.stdout).not.toContain('\f');
    });

    it('without -nopgbrk, each page is followed by a form-feed', async () => {
      const r = await runner.run('pdftotext /tmp/two.pdf -');
      expect(r.exitCode).toBe(0);
      const formFeeds = (r.stdout.match(/\f/g) ?? []).length;
      // 2 pages → 2 form-feeds (one after each page including the last)
      expect(formFeeds).toBe(2);
    });
  });

  // -------------------------------------------------------------------------
  // Spec: output file handling
  // -------------------------------------------------------------------------

  describe('spec: output file handling', () => {
    it('default output goes to <stem>.txt in same directory as input', async () => {
      const r = await runner.run('pdftotext /tmp/one.pdf');
      expect(r.exitCode).toBe(0);
      const out = new TextDecoder().decode(vfs.readFile('/tmp/one.txt'));
      expect(out).toContain('Hello World');
    });

    it('explicit output file path is respected', async () => {
      const r = await runner.run('pdftotext /tmp/one.pdf /tmp/custom.txt');
      expect(r.exitCode).toBe(0);
      const out = new TextDecoder().decode(vfs.readFile('/tmp/custom.txt'));
      expect(out).toContain('Hello World');
    });

    it('- as output sends text to stdout (not a file)', async () => {
      const r = await runner.run('pdftotext /tmp/one.pdf -');
      expect(r.exitCode).toBe(0);
      expect(r.stdout).toContain('Hello World');
    });

    it('nothing is written to stdout when outputting to a file', async () => {
      const r = await runner.run('pdftotext /tmp/one.pdf /tmp/out.txt');
      expect(r.exitCode).toBe(0);
      expect(r.stdout).toBe('');
    });
  });

  // -------------------------------------------------------------------------
  // Spec: accepted flags that are ignored (layout modes)
  // These must not cause errors — they're accepted for compatibility.
  // -------------------------------------------------------------------------

  describe('spec: accepted but ignored flags', () => {
    for (const flag of ['-layout', '-raw', '-nodiag', '-htmlmeta', '-tsv',
                        '-bbox', '-bbox-layout', '-cropbox', '-q', '-listenc']) {
      it(`${flag} is accepted without error`, async () => {
        const r = await runner.run(`pdftotext ${flag} /tmp/one.pdf -`);
        expect(r.exitCode).toBe(0);
        expect(r.stdout).toContain('Hello World');
      });
    }

    for (const [flag, val] of [['-enc', 'UTF-8'], ['-eol', 'unix'],
                                ['-r', '72'], ['-x', '0'], ['-y', '0'],
                                ['-W', '0'], ['-H', '0'],
                                ['-fixed', '1.0'], ['-colspacing', '0.7']]) {
      it(`${flag} ${val} is accepted without error`, async () => {
        const r = await runner.run(`pdftotext ${flag} ${val} /tmp/one.pdf -`);
        expect(r.exitCode).toBe(0);
        expect(r.stdout).toContain('Hello World');
      });
    }
  });

  // -------------------------------------------------------------------------
  // Spec: error handling
  // -------------------------------------------------------------------------

  describe('spec: error handling', () => {
    it('missing file exits 1', async () => {
      const r = await runner.run('pdftotext /tmp/no-such-file.pdf -');
      expect(r.exitCode).toBe(1);
    });

    it('missing file prints error to stderr', async () => {
      const r = await runner.run('pdftotext /tmp/no-such-file.pdf -');
      expect(r.stderr).toContain('no-such-file.pdf');
    });

    it('missing file produces no stdout', async () => {
      const r = await runner.run('pdftotext /tmp/no-such-file.pdf -');
      expect(r.stdout).toBe('');
    });
  });

  // -------------------------------------------------------------------------
  // Real-world: "Attention Is All You Need" (arxiv 1706.03762)
  // 15-page paper, tested against Poppler 26.03.0
  // -------------------------------------------------------------------------

  describe('real-world: Attention Is All You Need (arxiv 1706.03762)', () => {
    it('extracts the paper title from page 1', async () => {
      if (!ATTENTION_PDF_BYTES) return;
      const r = await runner.run('pdftotext -f 1 -l 1 /tmp/attention.pdf -');
      expect(r.exitCode).toBe(0);
      expect(r.stdout).toContain('Attention Is All You Need');
    });

    it('extracts author names from page 1', async () => {
      if (!ATTENTION_PDF_BYTES) return;
      const r = await runner.run('pdftotext -f 1 -l 1 /tmp/attention.pdf -');
      expect(r.exitCode).toBe(0);
      expect(r.stdout).toContain('Vaswani');
    });

    it('3-page range produces exactly 3 form-feeds', async () => {
      if (!ATTENTION_PDF_BYTES) return;
      const r = await runner.run('pdftotext -f 1 -l 3 /tmp/attention.pdf -');
      expect(r.exitCode).toBe(0);
      const formFeeds = (r.stdout.match(/\f/g) ?? []).length;
      expect(formFeeds).toBe(3);
    });

    it('-nopgbrk removes all form-feeds', async () => {
      if (!ATTENTION_PDF_BYTES) return;
      const r = await runner.run('pdftotext -nopgbrk -f 1 -l 3 /tmp/attention.pdf -');
      expect(r.exitCode).toBe(0);
      expect(r.stdout).not.toContain('\f');
    });

    it('all 15 pages produce substantial text output', async () => {
      if (!ATTENTION_PDF_BYTES) return;
      const r = await runner.run('pdftotext /tmp/attention.pdf -');
      expect(r.exitCode).toBe(0);
      expect(r.stdout.length).toBeGreaterThan(10000);
    });

    it('default output writes to attention.txt', async () => {
      if (!ATTENTION_PDF_BYTES) return;
      const r = await runner.run('pdftotext -f 1 -l 1 /tmp/attention.pdf');
      expect(r.exitCode).toBe(0);
      const out = new TextDecoder().decode(vfs.readFile('/tmp/attention.txt'));
      expect(out).toContain('Attention Is All You Need');
    });
  });
});
