/**
 * Tool package manifests — per-tool install directives shipped next
 * to the `.wasm` binary as `<name>.manifest.json`.  Generated by the
 * host build (cpcc-level Makefiles in packages/c-ports/<port>/) and
 * copied into wasmDir alongside the binary they describe.
 *
 * The orchestrator-side install is intentionally minimal: copy any
 * declared sidecar files into the VFS at the declared paths, register
 * the binary as a multicall dispatcher when applets are listed, and
 * create any declared symlinks.  Pure WASI binaries with no sidecars
 * (e.g. the Rust coreutils) ship without a manifest and the install
 * pass is a no-op for them.
 *
 * Same shape will be consumed by `pkg install` once that path lands —
 * for now the only entry point is sandbox boot.
 */

import type { VFS } from '../vfs/vfs.js';
import type { ProcessManager } from '../process/manager.js';
import type { PlatformAdapter } from '../platform/adapter.js';

export interface ManifestFileEntry {
  /** Filename next to the .wasm in wasmDir. */
  src: string;
  /** Absolute VFS path to install at. */
  dest: string;
}

export interface ManifestSymlink {
  /** Symlink target (the path it points to). */
  target: string;
  /** Absolute VFS path of the symlink to create. */
  link: string;
}

export interface ManifestMulticall {
  /** Applet names dispatched by argv[0] inside this binary. */
  applets: string[];
}

export interface PackageManifest {
  /** Tool name — must match the .wasm basename. */
  name: string;
  /** Sidecar data files to install into the VFS at sandbox boot. */
  files?: ManifestFileEntry[];
  /** Multicall dispatch — overrides per-applet registry entries with this binary. */
  multicall?: ManifestMulticall;
  /** Extra symlinks to create after install. */
  symlinks?: ManifestSymlink[];
}

/** Fetch and parse `<name>.manifest.json`, or return null if absent. */
export async function loadManifest(
  adapter: PlatformAdapter,
  wasmDir: string,
  name: string,
): Promise<PackageManifest | null> {
  if (!adapter.readDataFile) return null;
  const bytes = await adapter.readDataFile(wasmDir, `${name}.manifest.json`);
  if (!bytes) return null;
  const text = new TextDecoder().decode(bytes);
  const parsed = JSON.parse(text) as PackageManifest;
  if (parsed.name !== name) {
    throw new Error(
      `Manifest name mismatch: file ${name}.manifest.json declares name='${parsed.name}'`,
    );
  }
  return parsed;
}

/**
 * Apply a manifest at sandbox-boot time.  Idempotent within a single
 * boot — callers loop over scanned tools and call this for each one
 * that has a manifest.  Tool registration (single-binary registerTool)
 * has already happened; this pass layers on the install side-effects.
 */
export async function applyManifest(
  manifest: PackageManifest,
  ctx: { mgr: ProcessManager; vfs: VFS; adapter: PlatformAdapter; wasmDir: string },
  wasmPath: string,
): Promise<void> {
  if (manifest.files?.length) {
    await installFiles(manifest.files, ctx);
  }
  if (manifest.multicall?.applets.length) {
    ctx.mgr.registerMulticallTool(manifest.name, wasmPath, manifest.multicall.applets);
  }
  if (manifest.symlinks?.length) {
    installSymlinks(manifest.symlinks, ctx.vfs);
  }
}

async function installFiles(
  entries: ManifestFileEntry[],
  ctx: { vfs: VFS; adapter: PlatformAdapter; wasmDir: string },
): Promise<void> {
  if (!ctx.adapter.readDataFile) return;
  for (const entry of entries) {
    const bytes = await ctx.adapter.readDataFile(ctx.wasmDir, entry.src);
    if (!bytes) continue;
    const dir = entry.dest.replace(/\/[^/]*$/, '');
    ctx.vfs.withWriteAccess(() => {
      if (dir) ctx.vfs.mkdirp(dir);
      ctx.vfs.writeFile(entry.dest, bytes);
    });
  }
}

function installSymlinks(symlinks: ManifestSymlink[], vfs: VFS): void {
  vfs.withWriteAccess(() => {
    for (const sym of symlinks) {
      try { vfs.unlink(sym.link); } catch { /* not present */ }
      vfs.symlink(sym.target, sym.link);
    }
  });
}
